export const ActionType = {
	//Task Action Type
	GET_TASK: 'GET_TASK',
	CREATE_TASK: 'CREATE_TASK',
	EDIT_TASK: 'EDIT_TASK',
	DELETE_TASK: 'DELETE_TASK',
	CHANGE_STATUS: 'CHANGE_STATUS',
	FILTER_DONE_TASKS: 'FILTER_DONE_TASKS',
	CLEAR_TASK_ITEM: 'CLEAR_TASK_ITEM',

	//Modal Action Type
	TOGGLE_MODAL: 'TOGGLE_MODAL',
	TOGGLE_SHOW_DETAIL_TASK: 'TOGGLE_SHOW_DETAIL_TASK'
};
